name: test_screens
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  intl: ^0.19.0
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils/
  filename: assets.dart
  field_prefix: null
